services:
  wishlist-api:
    build: .
    container_name: wishlist-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://user:pass@mongo-db:27017/test?authSource=admin
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=test
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: